//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCScustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyModule
    {
        public System.Guid CompanyModuleID { get; set; }
        public Nullable<System.Guid> CompanyKey { get; set; }
        public Nullable<System.Guid> ModuleKey { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Modules Modules { get; set; }
    }
}
