//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCScustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTradeCharge
    {
        public System.Guid Pkey { get; set; }
        public System.Guid CustomerKey { get; set; }
        public Nullable<System.Guid> TradeKey { get; set; }
        public Nullable<System.Guid> SalesChargeTypeKey { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Don { get; set; }
        public Nullable<System.Guid> Dby { get; set; }
        public Nullable<decimal> Amt { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual SalesChargeType SalesChargeType { get; set; }
        public virtual Trade Trade { get; set; }
    }
}
