//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCScustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerLogin
    {
        public System.Guid UserKey { get; set; }
        public Nullable<System.Guid> CustomerKey { get; set; }
        public Nullable<System.Guid> ContactKey { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual CustomerContact CustomerContact { get; set; }
    }
}
