//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCScustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerLocation
    {
        public System.Guid CustomerLKey { get; set; }
        public Nullable<System.Guid> CustomerKey { get; set; }
        public Nullable<System.Guid> LocationKey { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Location Location { get; set; }
    }
}
