//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCScustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerLabor
    {
        public System.Guid Labor { get; set; }
        public System.Guid CustomerKey { get; set; }
        public Nullable<System.Guid> TradeKey { get; set; }
        public Nullable<decimal> Standard { get; set; }
        public Nullable<decimal> Emergency { get; set; }
        public Nullable<decimal> Holiday { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Trade Trade { get; set; }
    }
}
