//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCScustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentationSetup
    {
        public System.Guid ID { get; set; }
        public string Header { get; set; }
        public string Footer { get; set; }
        public string SignOffSheet { get; set; }
        public string PaymentTerms { get; set; }
        public string TermCondition { get; set; }
        public string QuoteConfiguration { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.Guid> CompanyKey { get; set; }
        public string EmailBodyWorkOrder { get; set; }
        public string EmailBodyInvoice { get; set; }
        public string WorkOrderHeader { get; set; }
        public string InvoiceHeader { get; set; }
        public string EstimateHeader { get; set; }
        public string SubjectWorkOrder { get; set; }
        public string SubjectEstimate { get; set; }
        public string SubjectInvoice { get; set; }
    }
}
