//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCScustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GridTitleDetail
    {
        public int DetailKey { get; set; }
        public Nullable<int> GridKey { get; set; }
        public Nullable<System.Guid> JobStatusKey { get; set; }
    
        public virtual GridTitle GridTitle { get; set; }
        public virtual JobStatus JobStatus { get; set; }
    }
}
