//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCScustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobFile
    {
        public System.Guid FileKey { get; set; }
        public System.Guid JobKey { get; set; }
        public Nullable<System.Guid> DocumentTypeKey { get; set; }
        public Nullable<System.Guid> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public string Comment { get; set; }
        public string Title { get; set; }
        public string Remarks { get; set; }
        public byte[] FileContent { get; set; }
        public string FileType { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string FileName { get; set; }
    
        public virtual DocumentType DocumentType { get; set; }
        public virtual Job Job { get; set; }
        public virtual StaffList StaffList { get; set; }
    }
}
