//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCScustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobLocation
    {
        public System.Guid JobLocationKey { get; set; }
        public Nullable<System.Guid> JobKey { get; set; }
        public Nullable<System.Guid> LocationKey { get; set; }
        public Nullable<System.Guid> ContactKey { get; set; }
        public string Address { get; set; }
        public Nullable<int> CityKey { get; set; }
        public Nullable<int> StateCode { get; set; }
        public string ZIPcode { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.Guid> CompanyKey { get; set; }
    
        public virtual CityList CityList { get; set; }
        public virtual Job Job { get; set; }
        public virtual Location Location { get; set; }
        public virtual LocationContact LocationContact { get; set; }
        public virtual StateList StateList { get; set; }
    }
}
