//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCScustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRequestAttachments
    {
        public System.Guid PKey { get; set; }
        public System.Guid RequestKey { get; set; }
        public Nullable<System.Guid> DocumentTypeKey { get; set; }
        public byte[] DocFile { get; set; }
        public string FileType { get; set; }
        public string Filename { get; set; }
    
        public virtual DocumentType DocumentType { get; set; }
        public virtual JobRequest JobRequest { get; set; }
    }
}
