//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCScustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSalesInvoiceDetail
    {
        public System.Guid DetailKey { get; set; }
        public System.Guid InvoiceKey { get; set; }
        public Nullable<System.Guid> ChargeTypeKey { get; set; }
        public Nullable<System.Guid> JobKey { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Amt { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual JobSalesInvoice JobSalesInvoice { get; set; }
        public virtual SalesChargeType SalesChargeType { get; set; }
    }
}
