//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCScustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSalesInvoiceEstimateStatus
    {
        public System.Guid Pkey { get; set; }
        public System.Guid InvoiceKey { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CustomerKey { get; set; }
        public Nullable<System.Guid> JobKey { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> Accept { get; set; }
        public Nullable<bool> Decline { get; set; }
        public Nullable<bool> Resubmit { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Job Job { get; set; }
        public virtual JobSalesInvoice JobSalesInvoice { get; set; }
    }
}
