//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCScustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobStatusUsergroup
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> JobStatusID { get; set; }
        public System.Guid UserGroupKey { get; set; }
    
        public virtual JobStatus JobStatus { get; set; }
        public virtual Usergroup Usergroup { get; set; }
    }
}
