//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCScustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSignOff
    {
        public System.Guid SignoffKey { get; set; }
        public Nullable<System.Guid> LocationKey { get; set; }
        public Nullable<System.Guid> JobKey { get; set; }
        public Nullable<System.Guid> CustomerKey { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsServiceLocation { get; set; }
        public Nullable<bool> IsTimeIn { get; set; }
        public Nullable<bool> IsTimeOut { get; set; }
        public Nullable<bool> IsServiceDate { get; set; }
        public string TimeIn { get; set; }
        public string TimeOut { get; set; }
        public string ServiceDate { get; set; }
        public Nullable<bool> IsManagerName { get; set; }
        public Nullable<bool> IsManagerSign { get; set; }
        public Nullable<bool> IsStoreStamp { get; set; }
        public string ManagerName { get; set; }
        public string ManagerSign { get; set; }
        public string StoreStamp { get; set; }
        public Nullable<bool> IsAttention { get; set; }
        public string Attention { get; set; }
        public Nullable<bool> IsDescription { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Job Job { get; set; }
        public virtual Location Location { get; set; }
    }
}
