//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCScustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobVendor
    {
        public System.Guid PKey { get; set; }
        public System.Guid JobKey { get; set; }
        public Nullable<System.Guid> VendorKey { get; set; }
        public Nullable<System.Guid> TradeKey { get; set; }
        public Nullable<decimal> HourlyRate { get; set; }
        public Nullable<decimal> TripCharge { get; set; }
        public Nullable<decimal> ServiceCharge { get; set; }
        public Nullable<System.Guid> ContactKey { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string Remarks { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual Trade Trade { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual VendorContact VendorContact { get; set; }
    }
}
