//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCScustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationContact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LocationContact()
        {
            this.Job = new HashSet<Job>();
            this.JobLocation = new HashSet<JobLocation>();
            this.JobRequest = new HashSet<JobRequest>();
        }
    
        public System.Guid ContactKey { get; set; }
        public System.Guid LocationKey { get; set; }
        public string Cname { get; set; }
        public string Title { get; set; }
        public string Phone { get; set; }
        public string PhoneEXT { get; set; }
        public string FAX { get; set; }
        public string ALTPhone { get; set; }
        public string ALTPhoneEXT { get; set; }
        public string Email { get; set; }
        public bool IsDefault { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.Guid> CompanyKey { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobLocation> JobLocation { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobRequest> JobRequest { get; set; }
    }
}
