//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCScustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StaffList()
        {
            this.CustomerAttachments = new HashSet<CustomerAttachments>();
            this.CustomerMesseging = new HashSet<CustomerMesseging>();
            this.CustomerNote = new HashSet<CustomerNote>();
            this.EmailConfiguration = new HashSet<EmailConfiguration>();
            this.JobAccountManager = new HashSet<JobAccountManager>();
            this.JobSalesInvoice = new HashSet<JobSalesInvoice>();
            this.JobTechnician = new HashSet<JobTechnician>();
            this.LocationAttachement = new HashSet<LocationAttachement>();
            this.LocationNotes = new HashSet<LocationNotes>();
            this.RCSmesseging = new HashSet<RCSmesseging>();
            this.TeamMember = new HashSet<TeamMember>();
            this.VendorAttachement = new HashSet<VendorAttachement>();
            this.VendorMesseging = new HashSet<VendorMesseging>();
            this.VendorNotes = new HashSet<VendorNotes>();
            this.JobFile = new HashSet<JobFile>();
        }
    
        public System.Guid PersonnelKey { get; set; }
        public string PID { get; set; }
        public string PName { get; set; }
        public string Mobile { get; set; }
        public string Mail { get; set; }
        public string Designation { get; set; }
        public string Department { get; set; }
        public byte[] Pic { get; set; }
        public string PicType { get; set; }
        public Nullable<System.Guid> CompanyKey { get; set; }
        public Nullable<System.Guid> Usergr { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsUser { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerAttachments> CustomerAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerMesseging> CustomerMesseging { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerNote> CustomerNote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailConfiguration> EmailConfiguration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobAccountManager> JobAccountManager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobSalesInvoice> JobSalesInvoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobTechnician> JobTechnician { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationAttachement> LocationAttachement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationNotes> LocationNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RCSmesseging> RCSmesseging { get; set; }
        public virtual Usergroup Usergroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamMember> TeamMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorAttachement> VendorAttachement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorMesseging> VendorMesseging { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorNotes> VendorNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobFile> JobFile { get; set; }
    }
}
