//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCScustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorNotes
    {
        public System.Guid NoteKey { get; set; }
        public Nullable<System.Guid> VendorKey { get; set; }
        public Nullable<System.Guid> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public string Comment { get; set; }
        public string Title { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string Remarks { get; set; }
    
        public virtual StaffList StaffList { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
