//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCScustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendor()
        {
            this.JobVendor = new HashSet<JobVendor>();
            this.JobWorkOrder = new HashSet<JobWorkOrder>();
            this.VendorAttachement = new HashSet<VendorAttachement>();
            this.VendorContact = new HashSet<VendorContact>();
            this.VendorMesseging = new HashSet<VendorMesseging>();
            this.VendorNotes = new HashSet<VendorNotes>();
            this.VendorTradeCharge = new HashSet<VendorTradeCharge>();
        }
    
        public System.Guid VendorKey { get; set; }
        public string Vname { get; set; }
        public string Address { get; set; }
        public string TaxID { get; set; }
        public string BillingLevel { get; set; }
        public Nullable<decimal> RadiusInMiles { get; set; }
        public Nullable<int> CityKey { get; set; }
        public Nullable<int> StateCode { get; set; }
        public string ZIPcode { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.Guid> CompanyKey { get; set; }
        public Nullable<System.DateTime> GLinsurenceExpiry { get; set; }
        public Nullable<System.DateTime> WCinsurenceExpiry { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
        public Nullable<long> NetID { get; set; }
    
        public virtual CityList CityList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobVendor> JobVendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobWorkOrder> JobWorkOrder { get; set; }
        public virtual StateList StateList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorAttachement> VendorAttachement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorContact> VendorContact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorMesseging> VendorMesseging { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorNotes> VendorNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorTradeCharge> VendorTradeCharge { get; set; }
    }
}
