//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCScustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorTrade
    {
        public System.Guid LaborKey { get; set; }
        public System.Guid VendorKey { get; set; }
        public Nullable<System.Guid> TradeKey { get; set; }
        public Nullable<decimal> HourlyRate { get; set; }
        public Nullable<decimal> TripCharge { get; set; }
        public Nullable<decimal> ServiceCharge { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual Trade Trade { get; set; }
    }
}
